-- passwords are the same as usernames, in hebrew
begin;

-- a real conversation about relationships
insert into conversations (id, talker_name, title, status)
values (1, 'ענת', 'אני מפחדת להרוס את היחסים', 'active');

insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני בטיפול ממושך להבראת דפוסים לא בריאים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אחרי שבמשך שנים החרבתי מערכות יחסים בזו אחר זו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ולא תכננתי להכנס למערכת היחסים הזו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואני מאד חרדה להחריב גם אותה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואני סובלת, ליטרלי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כאב');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אמיתי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה יחריב את היחסים?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שאני אחזור על השגיאות');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שאני לא אצליח בחיים האישיים שלי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וזה יהפוך אותי לבן אדם שלא ראוי לחיות איתו');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה יהפוך אותך לאדם שלא ראוי לחיות איתו?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שאני אתקע, שאני לא אתקדם, שאני לא אוכל לתרום במידה שווה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'הקטע הכלכלי מפריע לי באופן מיוחד');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה קורה בתחום הכלכלי?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'דווקא עשיתי קפיצה לא רעה בשנה פלוס האחרונות');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני לא יכולה להגיע לרמות שכר, זה נורא מפגר');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כשאני קוראת את המשפטים של עצמי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל אלהים כמה שזה כואב');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה זה אומר בשבילך שאת לא יכולה להגיע לרמות השכר של חבר שלך?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שאני לא יכולה לתרום באותה המידה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ליחסים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לחיים משותפים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'הוא יודע שאת מקנאה?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ברור');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מגניב!');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל זה לא יוצא עליו בלייב');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'למה לא?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'למדתי להוציא את זה על אנשים אחרים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כשאני מרגישה שהמפלצת מרימה את ראשה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני פשוט תופסת ממנו מרחק');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'למה את קוראת לזה "להוציא"?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'להגיד מה שאני באמת חושבת ומרגישה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'הוא אף פעם לא רואה אותי מתפרקת, רק אנשים אחרים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כי ההתפרקויות החריבו יחסים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'בעבר');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אחד הדפוסים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אז את מתרחקת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'נכון');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'בנסיון לשמור על היחסים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'נכון?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אמת');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'תקראי את זה רגע שוב');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'קראתי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'להתרחק בשביל לשמור על היחסים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'נכון');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כי יש לי הרגשה שאם אני אוציא את הדברים החוצה כמו שהם היחסים לא יחזיקו מעמד');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כמו שהיחסים הקודמים לא החזיקו מעמד');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'סיפרת בשיחה קודמת שהוא התאהב בך כשסיפרת לו את הדברים הכי רעים עלייך');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'נכון');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא מדויק -');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מה שקרה הוא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שסיפרתי דברים רעים כי לא רציתי לעמוד בפני הדילמה הזאת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וזה דווקא מה שקרב בינינו');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אני רוצה להגיד לך שאת תותחית על חלל');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'רק על הקטע הזה שנכנסת בעובי הקורה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'בשתי דקות של שיחה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'תודה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'בבקשה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אוקיי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אז כשהכרתם, דברים שסיפרת לו שחשבת שירחיקו אותו ממך, גרמו לו להתקרב');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'נכון');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ומה קורה עכשיו?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה שונה עכשיו?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה נעצר');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני לא יכולה להוציא את מה שנראה בעיני מפלצת');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אז מה מפלצתי בך?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני קנאית');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'יש לי מצבי רוח רעים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני לא רוצה להרגיש שאני תופסת את כל המקום');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ולא נותנת מקום');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'יש לי חרדות המוות מלא להצליח');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'יש לי היסטוריה לא מפוארת ודפוסי התנהגות שממש פחיד אותי שהם יחזרו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'נראה לי שסיכמתי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה הכי נורא מכל אלה?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שאלה טובה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'קשה לי להגיד');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אולי הקנאה,');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'היא לא הכי נוראה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל היא הכי מכאיבה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וכשהיא מכאיבה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני יודעת שהיא לא הגיונית');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל היא ממש מכאיבה לי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה את הכי מפחדת שהוא ידע?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'איך הקנאה שלי נראית');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ואיך היא נראית?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'רע');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ספרי לי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני שונאת אותן');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אותן?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כן');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'נשים אחרות?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כן');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'יש מישהי ספציפית?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'יש הרבה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'הרבה ספציפיות, או כל בחורה שמסתכלת עליו?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'הרבה ספציפיות');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'הקנאה זה מה שהרס את היחסים הקודמים שלך?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ממש לא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל הכעס');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'והדרך שביטאתי אותו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כן');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ועל מה כעסת?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וואו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'על מיליון דברים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה הדבר הראשון שקופץ לך לראש?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', '*****');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שתמות');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה פשוט גם גילוי של קנאה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'על מה כעסת עליה?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שהיא באה ונכנסה לי לחיים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ודרסה אותי בניסיון להשיג את מה שהיא רצתה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שהיא נכנסה לטריטוריה שלי, לבית שלי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ודרכה עלי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אני רוצה לשמוע יותר על *****');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה בדיוק היא עשתה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ומה בדיוק הרגשת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'טוב');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה נחלק לשני חלקים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'החלק הראשון הוא כשעוד הייתי עם *****');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'נכנסתי הביתה ותפסתי אותם על חם כמו בסרטים');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'הפרעתי להם באמצע');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'והחלק השני היה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שהוא הלך אליה וגר אצלה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שזה כבר לא כעס עליה אלא עליו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה כבר לא מזיז לי היום');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ובפעם הראשונה לא כעסת עליו?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'רק עליה?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כן');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'רק עליה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'לא ראית בו אחראי?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ממש ככה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'לא ראית אותו ממטר');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'דווקא ראיתי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אחרי זה, בפעם השניה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ראיתי אותו גם');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ומה קורה לך במערכת היחסים הנוכחית?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'תפסת את ***** עם מישהי?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ממש לא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני מרגישה בעיקר כאב');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'בכל מיני סיטואציות');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כאב פיזי ממש');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'איפה?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'איפה בגוף?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'כן');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'בבטן, בחזה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כשאני רואה כל מיני דברים או עדה לכל מיני דברים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה את רואה שמקפיץ לך את הכאב?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אז הדוגמה העיקרית היא *****');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואיך שהיא מתנהגת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מהיום שהכרנו בערך');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מה שמקפיץ לי...');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שהיא מזמינה אותו לארוחות ערב לבד');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שהיא אומרת לי שהיא פספסה הזדמנות לאהבה אמיתית שהיתה "כמעט"');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שהיא מסרבת פאקינג ללכת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וחייבת להשאר בתמונה כל הזמן');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל זה לא רק היא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה גם כל מיני אקסיות שעושות "לייקים" לתמונות');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כוס אמא של העידן המודרני');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', '');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אז את רוצה את ***** רק לעצמך?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כן ולא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'בן אדם "טוב" תמיד ימשוך תשומת לב חיובית');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה בא עם החבילה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה החלק ההגיוני');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני פשוט לא יודעת להתמודד עם זה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'את רוצה שזה לא יגרום לך כאב?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'בדיוק');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'למה?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כי אני סובלת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואני רוצה להפסיק לסבול');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'האם את סובלת בגלל שכואב, או שאת סובלת בגלל שאת לא רוצה שיכאב?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'את מבינה את הכוונה שלי?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אוקיי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'נניח שיש חייל');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'והוא נפצע');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'והוא שוכב בבית החולים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'וכואב לו נורא');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'בפצעים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אבל בנוסף לכל זה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'הוא חושב שהוא בכלל לא היה אמור להפצע');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אם הוא רק היה מתקופף');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כן, מבינה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אז השאלה היא האם הבעיה היא הכאב, או המחשבה שמתלווה אליו?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא. זה הכאב.');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'יש עוד משהו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'עכשיו כשאני חושבת על זה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'תמיד חשבתי על שני הדברים אבל אף פעם לא קישרתי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מאד מפריע לי שבעולם "הוירטואלי"');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אף אחד לא יודע מי אני');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואני מרגישה שזה לא לגיטימי לבוא ולדרוש שזה יהיה אחרת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואני מרגישה שזה לא לגיטימי שאני אגיד את זה אפילו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מי שמכיר את ***** בעולם הוירטואלי לא מכיר אותי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וזה הולך ביחד');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אני לא בטוח שהבנתי מה הבנת');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה הבנת?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שזה לא רק הן');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה גם דברים בדרך שלו שמפריעים לי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואני לא מסוגלת אפילו להגיד את זה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כי רק מלקרוא את השורות שאני כותבת עכשיו');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה נראה לי לא לגיטימי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'זה נורא כיף לראות אותך עובדת');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ומתעמקת');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ומחפשת');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כן. ועכשיו כואבת לי הבטן. והחזה. והלב.');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מהדברים הדבילים האלה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'או');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'רגע');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'עצרי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'למה אלה דברים דביליים?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אלה הרגשות שלך');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'נכון');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אוקיי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אז הרגשות שלך דביליות?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'בואי נסתכל על משהו רגע');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה הדבר שהכי מפחיד אותך להגיד ל*****?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'קשה לי להצביע על משפט אחד');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'בערך כל מה שאמרתי לך עכשיו');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ובכל זאת');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה הדבר שהחשיפה שלו מעוררת הכי הרבה כאב?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אולי זה הדבר שהכי מפחיד אותי להגיד');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שההתנהגות החשאית הזאת של *****');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מזמינה את זה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'מזמינה אותן');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ודבר שני');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני רוצה שיתגאו בי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'למה חשוב לך ש***** יתגאה בך?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אררר');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שאלה קשה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני מניחה שזה חוזר למה שדיברנו עליו בהתחלה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'להרגיש בן אדם ראוי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ופה יש גם חלק שהוא שלי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אם ***** יתגאה בך, את תרגישי ראויה?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'או שאם תרגישי ראויה, אז ***** יתגאה בך?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שניהם');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אבל ברור שאני צריכה ללמוד להרגיש ראויה ללא קשר');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'איך יראו החיים שלך כשתרגישי לגמרי ראויה?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה יקרה?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'קלילים ונעימים');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', '');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'ואני לא אתעצבן מאיזה סתומה שעושה לייק');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני לא אפחד ואני לא אתרגש מהשטויות האלה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אהו!');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'נכון');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'הפאקצות ימשיכו להציק');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', '***** ימשיך להסתיר');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'ואת?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'זה לא יזיז לי');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'כי אני ארגיש כזה בן אדם נפלא');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שאני לא אצטרך את החיזוקים האלה מבחוץ');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה שלום הכאב?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וואללה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'יש עוד עבודה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אני יודעת שזה הכיוון');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה את יכולה לעשות בכדי להרגיש יותר ראויה?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'משהו שלא תלוי באף אחד אחר..');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא יודעת, זה מעסיק אותי המון');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'לא משהו חיצוני כנראה כי דברים דווקא מסתדרים לי מצויין חיצונית');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'וזה לא עוזר');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה קרה בשיחה הזאת עכשיו?');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'מה שיפר את ההרגשה שלך?');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'שדימיינתי את המצב הרצוי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'אז בואי תקחי את זה צעד אחד קדימה');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'תתארי בכתב איך יראו החיים שלך');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'כשתרגישי ראויה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אוקיי');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'שיעורי בית');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'אחלה');
insert into messages (conversation_id, author, type, text) values (1, 'ענת', 'talker', 'חפרנו');
insert into messages (conversation_id, author, type, text) values (1, 'אלון', 'listener', 'היה כיף חיים');

-- a real conversation about career

insert into conversations (id, talker_name, title, status)
values (2, 'תומר', 'אני מתלבט אם לקחת אחריות ולהיות מנהל', 'active');

insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אני בהתלבטות מאד קשה, ורוצה קצת שיקופים');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'בעקבות הסדנה, בהמלצה של המאמנת, התחלתי קצת לכתוב דברים (ואני לא מתכוון לקוד)');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ופתאום שמתי לב שיש לי עניין לא פתור לגבי החלפת התפקיד שלי בעבודה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואללה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מעניין');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ואני מאד מתלבט אם הרצון להחליף תפקיד נובע מרצון אמיתי להתנתק מתפקיד רשמי וניהולי ולהשתחרר מתכנון והערכות זמנים ואחריות, או...');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'או שזה פשוט תירוץ לחשוב שאם רק אחליף תפקיד, הכל יהיה יותר טוב (ומושלם).');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ומה יצא לך בכתיבה?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זהו, השאלה עלתה, ועדיין אין תשובה. אבל יש לי הרגשה מאד חזקה שזה לא באמת יעשה שינוי משמעותי.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫איזה שינוי אתה רוצה שיקרה?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ובאותה מידה אני יכול להישאר בתפקיד, ולעשות אותו איך שאני חושב שצריך לעשות אותו.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ההיפך: ראיתי המון הערכה על הכנות.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אני רוצה לחזור על שאלה שלי - מה אתה רוצה שיקרה?');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫הרי עשית את הצעד הזה בשביל להשיג משהו, מה זה?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', '(חושב)');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫רק אם תדע את התשובה, תוכל לדעת האם הצעד מקרב אותך לשם או לא..');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אני רוצה להרגיש טוב עם מה שאני עושה. אני לא רוצה לעשות דברים בשביל לרצות אף אחד.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', ':)');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואיך זה קשור למציאות בחוץ?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'לא רוצה לרצות את הבוס שלי, ולא את הקולגות שלי.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ואני מספר לעצמי שהם מצפים ממני לעשות דברים באופן מסויים, לא כמו שאני חושב שצריך לעשות.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ובנושא הטכני, יש לי ביטחון עצמי גבוה שאני יודע מה נכון');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫יצא לך לחשוב על איך היית רוצה לעשות את התפקיד בעולם מושלם?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'למרות שהיתה לי תקופה קשה גם בזה, כפי שסיפרתי לך');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫בלי ציפיות מאחרים ובלי רגשות אשם שלך?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'כן! בדיוק.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫איך זה יראה?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ובחודשים האחרונים אני מרגיש שאני עושה את התפקיד בצורה הכי טובה עד כה.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'לא עושה ישיבות עם האנשים פעם בשבוע "כי צריך"');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'לא עושה תכניות עבודה "כי צריך"');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'פשוט זורם');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ומה הבעיה עם זה?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זהו, שגיליתי שאין שום בעיה עם זה.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'להיפך');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'פשוט האמנתי שאני לא מנהל טוב.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אני זוכר ש*** ב****** התפלא מאד כשאמרתי לי שאני לא חושב שאני מתאים להיות ראש צוות');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'הוא אמר שאני אחד הר"צ הכי טובים שלו');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אמרתי לעצמי שבוא סתם שקרן ורוצה שקט תעשייתי');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ואולי הוא לא שיקר');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מתי הגעת למסקנה שאתה ראש צוות לא טוב?');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה היה לפני ****** אני מניח..');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'נראה לי שזה גם שריד מ******.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'שם הייתי פשוט "לא טוב".');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואו.. הרבה זמן עבר מאז');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'הייתי troublemaker');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫וזה בעיניך היום דבר לא טוב?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ולא שיתפתי פעולה עם אנשים, כי ידעתי איך לעשות הכל "נכון" והם לא.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'היום אני חושב שלהיות troublemaker זה פשוט לא אפקטיבי.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זה שוחק אותי ואת הסביבה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ולא משיג תוצאות חוץ מתסכול משני הצדדים');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫נכון');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואתה גם לא רוצה להיות כנוע');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ולעשות מה שאומרים לך ומה שמצפים ממך');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'נכון.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫והאמת איננה באמצע');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אבל עכשיו אני יכול לראות את הדברים דרך העיניים של אנשים אחרים');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ולהבין שאני יכול לעזור להם ולהרגיש טוב');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'בלי לרצות אותם');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואו!');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זה קרה לי השבוע כמה פעמים בעבודה.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה מטורף מה שאתה אומר');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אז רגע');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'וההרגשה היתה נפלאה, לעזור כי אני רוצה.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מה הבעיה?');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אמרת שיש בעיה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זהו שאין בעיה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אני לא רואה בעיה :)');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'יש בעיה קטנה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', 'אוקיי..');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'שאני חושש שאם אשאר בתפקיד, זה מתוך פחד של מה תהיה האלטרנטיבה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'כמו שהיה כשקיבלתי את התפקיד');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ולא מתוך רצון אמיתי');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ואת זה אני רוצה לחקור');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואתה מנסה להבין מהו רצון אמיתי ומהו פחד?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'בדיוק');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אוקיי');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫למה לפעול מתוך פחד זה לא נכון?');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה בהכרח לא נכון?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', '*צוחק*');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', ':)');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זה נראה לי כמו חולשה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אה..');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואתה לא יכול להפגין חולשה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫או לנהוג בחולשה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'הממ...');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זה לא העניין');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אוקיי..');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אין לי בעיה להפגין חולשה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫נכון');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אבל אני רוצה להתגבר על החולשה, ולא לתת לה להכתיב את ההחלטה שלי');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מה מפחיד אותך במצב שבו לא תהיה מנהל?');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫היום, איך שאתה?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', '(סלח לי דקה, הילדים צריכים משהו)');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אין בעיה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'חזרתי');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫כן');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אז מה מפחיד אותך?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'כמה דברים');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אחד, שיהיה לי מנהל שיהיה לי קשה לעבוד איתו, כי הוא ידרוש הרבה דברים או ייכנס לי לקרביים');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'דבר שני, שאני אתעסק יותר מדי בפרטים טכניים ולא אהיה במרכז העניינים (שזה גם יתרון וגם חסרון)');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אני רוצה לחזור רגע צעד אחורה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ברשותך');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אתה יכול לתאר לי את המצב האידיאלי שבו הייתי רוצה לעבוד?');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫בלי הגדרות תפקיד, בלי גבולות, בלי ציפיות');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫רק מה שאתה רוצה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אוקיי');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'סביבה תומכת של אנשים שסומכים אחד על השני');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ללא צורך בלוחות זמנים או התחייבות לתאריכים');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'עם הערכה ליצירתיות');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'עם אפשרות לעשות מנטורינג לאנשים וללמד');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אמרת משהו על להיות במרכז העניינים. זה גם חלק?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ברור. אני נהנה מזה שמעריכים אותי, אולי אפילו מעריצים');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫כל הכבוד על הכנות');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מותר לך לרצות שיעריצו אותך');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'כן, גיליתי את זה כבר');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אוקיי, מגניב, מה עוד?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אני רוצה סביבה שמעריכה דברים שחשובים בעיני, ולא דברים שרירותיים כמו "עוד גרסה מטופשת"');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'לעשות משהו שעוזר לאנשים, זה משמעותי.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אז מה שאתה אומר');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫הוא שאתה רוצה השפעה משמעותית על סביבת העבודה שלך');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫על האנשים שסביבך');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אתה רוצה תקשורת טובה עם האנשים שאתה עובד איתם');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואתה רוצה חופש');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫חופש ליצור ולעבוד עם אנשים');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫נכון?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'נכון');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אבל אני מספר לעצמי שלמנהל אין "חופש"');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'בגלל שהוא "אחראי"');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ואני מבין שזה לא נכון, אבל לא ברור לי מספיק איך זה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫איך הצלחת להפוך את אחריות להיות ההפך מחופש?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זהו, משהו אצלי תקוע בתחום הזה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'של בין אחריות לחופש');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'רגשות האשם האלה, שחופש זה חוסר אחריות');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מתי אחריות פוגעת בחופש?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'כשהיא מעיקה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ולא באה מתוכי אלא מבחוץ');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫וכשאתה אומר האחריות מעיקה עלי, אתה אחראי או קורבן?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ברור שקרבן');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫כשאתה אומר האחריות באה מבחוץ, אתה אחראי או קורבן?');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'קרבן. אני יודע.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫בראש');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫כן, זה קל בראש');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'בדיוק!!');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אני לא מצליח להרגיש את זה.');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זה בדיוק העניין');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אוקיי');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫לאט לאט');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫לא צריך לרוץ');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה משהו שיכול לקחת לו קצת זמן לנחות מהראש ללב');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫תנשום רגע');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫קח נשימה עמוקה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זה ממש כאילו אתה לידי');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫יחד עם הצמרמורות :)');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אתה רוצה להביא את התובנה בכוח');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫כי אתה יודע איזו תובנה אתה רוצה להביא');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אבל זה לא עובד ככה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫לצערינו, אנשי הראש');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'ממש ככה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אני רוצה לתת לך תרגיל אם בא לך');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'טוב');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫בדרך כלל כשאנחנו מתלבטים בין שתי אפשרויות, אנחנו חושבים על זה כצומת');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אבל בעצם זה יותר דומה לירידה ממחלף');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫יש דרך אחת שהיא דיפולט');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואחרת שאותה אנחנו יכולים לקחת אם נבחר');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'מאד מתחבר לזה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מה ברירת המחדל שלך כרגע בהקשר הזה?');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה לא פשוט..');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'זו שאלה טובה');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'כי אני יכול לנמק לשני כיוונים');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אוקיי, נשים את זה בצד לרגע');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫הרעיון של התרגיל הוא להתחייס ברצינות לכל אחת מהאפשרויות');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה כמו בעד / נגד');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫*נגד');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אבל אני אוהב את המונחים מחירים / תמורות');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫עבור כל אחת מהאפשרויות עושים טבלה עם שתי עמודות');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫מחירים בצד אחד');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫תמורות בצד השני');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫בשונה מבעד ונגד, מחירים ותמורות מאפשרים להתייחס לעניינים רגשיים');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אין פה שום דבר אובייקטיבי');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫לפחדים, חששות, ציפיות, אכזבות - לכל הדברים האלה יש מקום בשתי הטבלאות');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אני מבין');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫כשתמלא את הטבלאות, תסמן בכל עמודה את הדבר הכי חשוב שם');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫את התמורה הכי גדולה ללהיות מנהל');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫את המחיר הכי גדול');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫וכו''');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'חשבתי על טבלה, אבל לא ידעתי איזו. זה עוזר.');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה אמור לעזור לך להתפקס על מה שאתה מרגיש');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫יכול להיות יווצר מצב שבו שתי האפשרויות לא טובות');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה רק מצביע על כך שצריך לחפש פתרונות אחרים :)');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אוקיי');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'אני הולך לעבוד על זה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫אל תשכח לנשום');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫זה לא דחוף ברמת הדקות');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'תודה');
insert into messages (conversation_id, author, type, text) values (2, 'אלון', 'listener', '‫ואני פה אם אתה צריך אותי');
insert into messages (conversation_id, author, type, text) values (2, 'תומר', 'talker', 'תודה על ההקשבה');

commit;

.quit